version: '3.9'

services:
  db:
    container_name: drizzle-db
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
    volumes:
      - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql